package id.my.anciety.codever.security.codever

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put
import org.junit.Assert.assertEquals
import org.junit.Assert.assertThrows
import org.junit.Test

/** Static fixture generated by packages/security, never by the Kotlin implementation. */
class CrossLanguageFixtureTest {
    private val root = Json.parseToJsonElement(FIXTURE).jsonObject
    private val offer = PairingCodec.parseOffer(root.getValue("offer").jsonObject)
    private val request = PairingCodec.parseRequest(root.getValue("request").jsonObject)
    private val response = PairingCodec.parseResponse(root.getValue("response").jsonObject)

    @Test
    fun `verifies TypeScript pairing offer request response and certificate`() {
        assertEquals("gateway-1", PairingSecurity.verifyOffer(offer, offer.offer.gatewayKey, NOW).gatewayId)
        assertEquals("phone-1", PairingSecurity.verifyRequest(request, offer, NOW).deviceId)
        assertEquals(
            "certificate-cross-1",
            PairingSecurity.verifyResponse(
                response,
                offer,
                request,
                offer.offer.gatewayKey,
                NOW + 3,
            ).certificate.certificate.certificateId,
        )
    }

    @Test
    fun `opens TypeScript secure envelope with injected JVM recipient identity`() {
        val gateway = TestP256Identity.fromPrivateJwk(
            EcPublicJwk(GATEWAY_X, GATEWAY_Y),
            GATEWAY_D,
        )
        val signed = SecureEnvelopeCodec.parse(CanonicalJson.encode(root.getValue("envelope")))
        val opened = SecureEnvelopes.openSecureEnvelope(
            signed,
            gateway,
            request.request.deviceKey,
            SecureEnvelopeBindings(
                gatewayId = "gateway-1",
                conversationId = "conversation-1",
                direction = SecureEnvelopeDirection.DEVICE_TO_GATEWAY,
                senderDeviceId = "phone-1",
                recipientDeviceId = "gateway-device",
                senderKeyId = request.request.deviceKey.keyId,
                recipientKeyId = offer.offer.gatewayKey.keyId,
            ),
            InMemoryReplayStore(),
            NOW + 1,
        )
        assertEquals("TypeScript encrypted fixture 😀", opened.plaintext.jsonObject.getValue("body").toString().trim('"'))
    }

    @Test
    fun `pairing rejects expiry replay bad signature and unknown fields`() {
        assertCode(SecurityErrorCode.EXPIRED) {
            PairingSecurity.verifyOffer(offer, now = offer.offer.expiresAt)
        }

        val replay = InMemoryReplayStore()
        PairingSecurity.consumeOffer(offer, request, replay, NOW)
        assertCode(SecurityErrorCode.REPLAY) {
            PairingSecurity.consumeOffer(offer, request, replay, NOW)
        }

        val signatureBytes = Base64Url.decode(offer.signature.value).also {
            it[0] = (it[0].toInt() xor 1).toByte()
        }
        assertCode(SecurityErrorCode.INVALID_SIGNATURE) {
            PairingSecurity.verifyOffer(
                offer.copy(signature = offer.signature.copy(value = Base64Url.encode(signatureBytes))),
                now = NOW,
            )
        }

        val offerJson = CanonicalJson.encode(offer.toJson())
            .replaceFirst("\"offer\":{", "\"offer\":{\"unknown\":true,")
        assertThrows(IllegalArgumentException::class.java) { PairingCodec.parseOffer(offerJson) }
    }

    @Test
    fun `Gateway trust codec persists transport cursor and migrates legacy schema`() {
        val base = GatewayTrust(offer, request, response)
        val rotatedTransport = base.certificate.gatewayTransport.copy(
            deviceId = "GATEWAY2",
            ed25519 = "gateway-ed25519-fingerprint-2",
        )
        val rotated = base.copy(
            transportTrust = base.transportTrust.copy(
                currentTransport = rotatedTransport,
                lastIssuedAt = NOW + 10,
            ),
        )
        val restored = GatewayTrustCodec.decode(GatewayTrustCodec.encode(rotated))
        assertEquals(rotatedTransport, restored.transportTrust.currentTransport)
        assertEquals(NOW + 10, restored.transportTrust.lastIssuedAt)

        val legacy = CanonicalJson.bytes(buildJsonObject {
            put("schemaVersion", 1)
            put("offer", offer.toJson())
            put("request", request.toJson())
            put("response", response.toJson())
        })
        val migrated = GatewayTrustCodec.decode(legacy)
        assertEquals(base.certificate.gatewayTransport, migrated.transportTrust.currentTransport)
        assertEquals(
            maxOf(base.offer.offer.issuedAt, base.certificate.issuedAt),
            migrated.transportTrust.lastIssuedAt,
        )
    }

    @Test
    fun `pairing rejection must be Gateway signed and request bound`() {
        val gateway = TestP256Identity.fromPrivateJwk(
            EcPublicJwk(GATEWAY_X, GATEWAY_Y),
            GATEWAY_D,
        )
        val rejection = PairingRejection(
            offerId = offer.offer.offerId,
            requestId = request.request.requestId,
            requestDigest = PairingSecurity.requestDigest(request),
            gatewayId = offer.offer.gatewayId,
            code = PairingRejectionCode.GATEWAY_REJECTED,
            message = "Pairing was declined.",
            retryable = false,
            issuedAt = NOW + 3,
            expiresAt = NOW + 60_000,
        )
        val preimage = CanonicalJson.bytes(buildJsonObject {
            put("domain", "codever.pairing.rejection.v1")
            put("document", rejection.toJson())
        })
        val signed = SignedPairingRejection(
            rejection,
            PairingSignature(gateway.publicIdentity.keyId, Base64Url.encode(gateway.sign(preimage))),
        )
        assertEquals(
            PairingRejectionCode.GATEWAY_REJECTED,
            PairingSecurity.verifyRejection(signed, offer, request, NOW + 4).code,
        )
        assertCode(SecurityErrorCode.BINDING_MISMATCH) {
            PairingSecurity.verifyRejection(
                signed.copy(rejection = rejection.copy(requestId = "different-request")),
                offer,
                request,
                NOW + 4,
            )
        }
    }

    private fun assertCode(code: SecurityErrorCode, block: () -> Unit) {
        val error = assertThrows(CodeverSecurityException::class.java, block)
        assertEquals(code, error.code)
    }

    private companion object {
        const val NOW = 1_800_000_000_000L
        const val GATEWAY_X = "1siSvHSRoOQTkfn_uzHGRR7mlrF14hRSidQrrkSjQ7w"
        const val GATEWAY_Y = "JLwmVQAUZvm_JOBQI6wBY_h7sNz5TuA2ICpclQk3twA"
        const val GATEWAY_D = "IsKgdASANPgY8A1pTLjxZ2-pJDPesTHsyRZuK2UEsIg"
        val FIXTURE = """
{"offer":{"offer":{"kind":"codever.pairing.offer","version":1,"offerId":"offer-cross-1","gatewayId":"gateway-1","gatewayName":"Cross fixture 😀","gatewayKey":{"version":1,"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","publicKey":{"kty":"EC","crv":"P-256","x":"1siSvHSRoOQTkfn_uzHGRR7mlrF14hRSidQrrkSjQ7w","y":"JLwmVQAUZvm_JOBQI6wBY_h7sNz5TuA2ICpclQk3twA","ext":true,"key_ops":["verify"]}},"gatewayTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@gateway:example.org","deviceId":"GATEWAY1","ed25519":"gateway-ed25519-fingerprint"},"challenge":"QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ","allowedOperations":["prompt","cancel"],"issuedAt":1799999999000,"expiresAt":1800000060000},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"2cYqMy7-_fsEYcqRWjs-ZuxegOx7p6BM8mmNj0sKNs-jbtSOl508GlD5LheamURfb0xsC31DMvhDVn2H9UrIVg"}},"request":{"request":{"kind":"codever.pairing.request","version":1,"requestId":"request-cross-1","offerId":"offer-cross-1","offerDigest":"rBY4CnEkfR0zkPfo_9FHGt4yniN4VPVBIgENaHbIY1c","gatewayId":"gateway-1","deviceId":"phone-1","deviceName":"Fixture phone","deviceKey":{"version":1,"algorithm":"ES256","keyId":"5PI0S-TOtBve2GIOXQVW66lgJvUpCnOzYQ2d6W_FLUQ","publicKey":{"kty":"EC","crv":"P-256","x":"T0mIwuoNwfa4zeB9bNqX-j2bTWCyON-1DBgg1RDQgmI","y":"tUHY9iz2MDqODPBEWb1qDCuGEBjJws4u6rlRj1Nyfmc","ext":true,"key_ops":["verify"]}},"deviceTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@alice:example.org","deviceId":"PHONE1","ed25519":"phone-ed25519-fingerprint"},"requestedOperations":["prompt"],"issuedAt":1800000000000,"expiresAt":1800000030000},"signature":{"algorithm":"ES256","keyId":"5PI0S-TOtBve2GIOXQVW66lgJvUpCnOzYQ2d6W_FLUQ","value":"WzYPNe9tyBHIsbbo5QGNwzVOC1UGEhGnDfBa87CvJOQuP4qYKMzHLmd3rEJtcS9hmyXlghUvbz1bocghTqEKIA"}},"response":{"response":{"kind":"codever.pairing.response","version":1,"offerId":"offer-cross-1","requestId":"request-cross-1","requestDigest":"EJrolsd7CfrE19WOA80PiODaOZwYzCP-PAnsCC1yKdo","gatewayId":"gateway-1","activeDeviceCount":2,"certificate":{"certificate":{"kind":"codever.pairing.certificate","version":1,"certificateId":"certificate-cross-1","offerId":"offer-cross-1","offerDigest":"rBY4CnEkfR0zkPfo_9FHGt4yniN4VPVBIgENaHbIY1c","requestId":"request-cross-1","requestDigest":"EJrolsd7CfrE19WOA80PiODaOZwYzCP-PAnsCC1yKdo","gatewayId":"gateway-1","gatewayKeyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","gatewayTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@gateway:example.org","deviceId":"GATEWAY1","ed25519":"gateway-ed25519-fingerprint"},"deviceId":"phone-1","deviceName":"Fixture phone","deviceKey":{"version":1,"algorithm":"ES256","keyId":"5PI0S-TOtBve2GIOXQVW66lgJvUpCnOzYQ2d6W_FLUQ","publicKey":{"kty":"EC","crv":"P-256","x":"T0mIwuoNwfa4zeB9bNqX-j2bTWCyON-1DBgg1RDQgmI","y":"tUHY9iz2MDqODPBEWb1qDCuGEBjJws4u6rlRj1Nyfmc","ext":true,"key_ops":["verify"]}},"deviceTransport":{"homeserver":"https://matrix.example.org","roomId":"!private:example.org","userId":"@alice:example.org","deviceId":"PHONE1","ed25519":"phone-ed25519-fingerprint"},"allowedOperations":["prompt"],"issuedAt":1800000000001,"expiresAt":1800086400000},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"QNz8YUeaAA2zHUgmxaGTzQIngXx1o4ptWqfUyvmf3iQzKt3vAFK3zS2znPiFgjZrbEiZQTk5YBgKxXVG8ZIhTQ"}},"issuedAt":1800000000002,"expiresAt":1800000090000},"signature":{"algorithm":"ES256","keyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","value":"cIbYQp6Rg17pGKRo0pSjiNeLxMsyiKz2lC5VEiqSip5EG3lXChmnFan-_ZSGv45CfhOpC_OMRPgF3C1FVNHxXg"}},"envelope":{"envelope":{"kind":"codever.secure-envelope","version":1,"envelopeId":"envelope-cross-1","contentType":"io.codever.matrix-content.v1","gatewayId":"gateway-1","conversationId":"conversation-1","direction":"device_to_gateway","senderDeviceId":"phone-1","recipientDeviceId":"gateway-device","senderKeyId":"5PI0S-TOtBve2GIOXQVW66lgJvUpCnOzYQ2d6W_FLUQ","recipientKeyId":"MsGTFCvsPKYo6KybfH4t9cOai5kX99MDFyG5fJ4cs94","issuedAt":1800000000000,"expiresAt":1800000120000,"nonce":"TTqUT-WTd_idpuLB","ciphertext":"BVOkFof0gjhamTL8AiLvdDyuXLEOTlMVGXeKzc3SqeaQXESr4y5nmnJEk2kc3UtWU0gpqsTsUsQtShD3JpxhkzXT08eh_Hci_lOGMtvUsM0y0oh6TZRY"},"signature":{"algorithm":"ES256","keyId":"5PI0S-TOtBve2GIOXQVW66lgJvUpCnOzYQ2d6W_FLUQ","value":"zmDuRA0pTz2HpwzCCH5nysTTKvzvEIOBtC-UNdhyFEbqhXbhg4NhztvvBisqU0pbdszGloMWop7a6rWO-Wb31Q"}}}
""".trimIndent()
    }
}
